//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseStatistic
    {
        //create a new coursestatistic instance for each question, so how many sudents are residents will be the name
        //count will be the answer

        public int Id { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
